"""add AI fields to bots and ai_conversation_turns

Revision ID: 4ada3ae2d27d
Revises: fc00fa1fa179
Create Date: 2026-05-22 15:42:43.095053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ada3ae2d27d'
down_revision: Union[str, None] = 'fc00fa1fa179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversation_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_turns_lookup', 'ai_conversation_turns', ['tenant_id', 'bot_id', 'slack_user_id'], unique=False)
    op.add_column('bots', sa.Column('ai_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('bots', sa.Column('ai_system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'ai_system_prompt')
    op.drop_column('bots', 'ai_enabled')
    op.drop_index('ix_ai_turns_lookup', table_name='ai_conversation_turns')
    op.drop_table('ai_conversation_turns')
    # ### end Alembic commands ###