"""add access_control_enabled to tenants

Revision ID: 5f70da57e74c
Revises: 2214dc96071f
Create Date: 2026-05-29 17:41:47.115914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f70da57e74c'
down_revision: Union[str, None] = '2214dc96071f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('access_control_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'access_control_enabled')
    # ### end Alembic commands ###