"""initial schema

Revision ID: f3548701d448
Revises: 
Create Date: 2026-04-27 14:18:33.444124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3548701d448'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slack_team_id', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slack_team_id'), 'tenants', ['slack_team_id'], unique=True)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('bot_token', sa.String(length=255), nullable=False),
    sa.Column('signing_secret', sa.String(length=255), nullable=False),
    sa.Column('slack_bot_user_id', sa.String(length=32), nullable=False),
    sa.Column('slack_app_id', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slack_bot_user_id', name='uq_bot_per_tenant')
    )
    op.create_index(op.f('ix_bots_slack_bot_user_id'), 'bots', ['slack_bot_user_id'], unique=False)
    op.create_index(op.f('ix_bots_tenant_id'), 'bots', ['tenant_id'], unique=False)
    op.create_table('slack_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('real_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slack_user_id', name='uq_user_per_tenant')
    )
    op.create_index(op.f('ix_slack_users_slack_user_id'), 'slack_users', ['slack_user_id'], unique=False)
    op.create_index(op.f('ix_slack_users_tenant_id'), 'slack_users', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('slack_channel_id', sa.String(length=32), nullable=True),
    sa.Column('slack_user_id', sa.String(length=32), nullable=True),
    sa.Column('slack_ts', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_bot_id'), 'messages', ['bot_id'], unique=False)
    op.create_index(op.f('ix_messages_slack_ts'), 'messages', ['slack_ts'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_slack_ts'), table_name='messages')
    op.drop_index(op.f('ix_messages_bot_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_slack_users_tenant_id'), table_name='slack_users')
    op.drop_index(op.f('ix_slack_users_slack_user_id'), table_name='slack_users')
    op.drop_table('slack_users')
    op.drop_index(op.f('ix_bots_tenant_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_slack_bot_user_id'), table_name='bots')
    op.drop_table('bots')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slack_team_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###